# NIFTY Options Trading System Configuration

# Trading Parameters
lot_size: 75

# Strategy Configuration
strategy:
  type: inside_bar
  sl: 30              # Stop Loss in points
  rr: 1.8             # Risk-Reward Ratio
  filters:
    volume_spike: true
    avoid_open_range: true
  
# Timeframe Configuration
timeframes:
  detection: "1h"     # Inside Bar detection timeframe
  confirmation: "15m" # Breakout confirmation timeframe

# Broker Configuration (overridden by secrets.toml)
broker:
  type: "angel"       # Options: "angel", "fyers"
  default_qty: 150     # Default quantity per trade (2 lots x 75)

# Position Management (point-based)
position_management:
  sl_points: 30          # initial SL in points (option price)
  trail_points: 10       # trailing step in points
  book1_points: 40       # book 50% at entry + 40 points
  book2_points: 54       # book remaining at entry + 54 points
  book1_ratio: 0.5       # 50% at first target

# Logging Configuration
logging:
  trades_file: "logs/trades.csv"
  errors_file: "logs/errors.log"
  log_level: "INFO"

# Market Data Configuration
market_data:
  polling_interval_seconds: 900  # 15 minutes
  max_retries: 3
  retry_delay_seconds: 5
  nifty_symbol: "NIFTY"  # Trading symbol for NIFTY index
  nifty_exchange: "NSE"
  data_window_hours_1h: 48
  data_window_hours_15m: 12

